### ISSUE TITLE
Warning: Cannot read property 'length' of undefined Use --force to continue.

### ISSUE THREAD

**Issue by stephenbe** [JohnCashmore/grunt-cssshrink#1]
This is my config :
```sh
		cssshrink: {
			all: {
				files: {
					'assets/styles/dist': ['assets/styles/dist/*.css']
				}
			}
		}
```
This is the error I am getting :
Warning: Cannot read property 'length' of undefined Use --force to continue.

Thank you

**Comment by marcusgraf** [comment]
I also have this issue. Have you solved it yet?

**Comment by JohnCashmore** [comment]
I haven't come across this before, can you try using the latest version of grunt and see if you have the same problem, i don't use length anywhere in the task
