### ISSUE TITLE
validity of the CSS 

### ISSUE THREAD

**Issue by throrin19** [JohnCashmore/grunt-cssshrink#2]
I Have this error if i try to use cssshrink on my css file :

```
Warning: Please check the validity of the CSS block starting from the line #14838 Used --force, continuing.
```

I check the line #14838 and this is the content at this point : 

```
/* Make clicks pass-through */
#nprogress {
  z-index: 99999;
  position: fixed;
}
#nprogress .bar {
  background: #61cae0;
  height: 3px;
}  /* <-- this is the line  14838 */
```

I don't understand the error.

**Comment by JohnCashmore** [comment]
I'd need the whole file to help, however i'd run your file through http://csslint.net/ to see if that spots anything
