### ISSUE TITLE
Object #<Object> has no method 'rgbaString' Use --force to continue.

### ISSUE THREAD

**Issue by kadishmal** [JohnCashmore/grunt-cssshrink#3]
Running `grunt` with `grunt-csssshrink` `v0.0.8` results in this error. Seems like the underlying `cssshrink` module `v0.0.5` has a nested dependency on `color-string` version `*` which has released a backward incompatible version `1.0.x` that breaks `grunt-csssshrink` builds.

**Comment by Dreyer** [comment]
Just encountered this error today. Seems like the issue is open here [stoyan/csscolormin/issues/4](https://github.com/stoyan/csscolormin/issues/4).

**Comment by JohnCashmore** [comment]
Hopefully this will get resolved soon but i am going to wait
